version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Configure commit message format
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group dependencies updates together
    groups:
      dependencies:
        patterns:
          - "*"

